Add support for returning multiple hash states
chancehudson/poseidon-lite pull request #3
Opened 2024-08-22 14:01 UTC by jimthematrix

This type of return is needed for building a poseidon based cipher, according to this paper https://drive.google.com/file/d/1EVrP3DzoGbmzkRmYnyEDcIQcXVU7GlOd/view. Equivalent to the latest poseidon functions in circomlibjs: https://github.com/iden3/circomlibjs/blob/main/src/poseidon_wasm.js#L15

2024-08-22 18:29 UTC, chancehudson commented
Hey thanks for the PR, could you drop [1f1ec34](https://github.com/chancehudson/poseidon-lite/pull/3/commits/1f1ec34f057727679a576a9d892b4d3db3917754) from this branch and put it elsewhere?

2024-08-22 18:43 UTC, chancehudson requested changes
This looks good to me, I added some suggested change for clarity. Thanks for the pr!

2024-08-22 18:43 UTC, chancehudson commented on src/poseidon/index.js
> +function poseidon(_inputs, opt, nOuts) {
```suggestion
function poseidon(_inputs, opt, nOuts = 1) {
```

2024-08-22 18:43 UTC, chancehudson commented on src/poseidon/index.js
> +  }
```suggestion
  if (nOuts === 1) {
    return state[0]
  } else if (nOuts > state.length) {
    return state.slice(0, nOuts)
  } else {
    throw new Error(`poseidon-lite: Invalid number of outputs requested ${nOuts}, max ${state.length}`)
  }
```
```

2024-08-22 18:43 UTC, chancehudson commented on test.mjs
> +  }
```suggestion
function check(a, b) {
  if (Array.isArray(a) && Array.isArray(b)) {
    if (a.length !== b.length) {
      throw new Error('Hash output state length mismatch')
    }
    for (let i = 0; i < a.length; i++) {
      check(a[i], b[i])
    }
  } else if (typeof a === 'bigint' && typeof b === 'bigint') {
    if (a !== b) throw new Error('Hash output mismatch')
  } else {
    throw new Error(`Output types mismatch: ${typeof a} ${typeof b}`)
  }
}
```

2024-08-23 01:15 UTC, jimthematrix commented on src/poseidon/index.js
> +  }
@chancehudson did you mean for the `else if` condition to be `nOuts <= state.length`?

2024-08-23 01:25 UTC, jimthematrix commented
@chancehudson all review comments should be addressed, including a minor (but critical) update from the suggested changes. Thanks for the prompt response!

2024-08-23 02:11 UTC, chancehudson commented on src/poseidon/index.js
> +  }
Oh yes, thanks for catching that

2024-08-23 02:13 UTC, chancehudson commented on scripts/prepublish.mjs
> +  export function poseidon${x + 1}(input: (bigint|number|string)[], nOuts: number): bigint
```suggestion
  export function poseidon${x + 1}(input: (bigint|number|string)[], nOuts?: number): bigint
```

Ah we should make this argument optional in ts.

2024-08-23 03:40 UTC, merged

2024-08-23 03:42 UTC, jimthematrix commented
@chancehudson will a new npm release be published soon?

2024-08-23 03:55 UTC, chancehudson commented
Included in `poseidon-lite@0.3.0`